name: GEDCOM

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./gedcom/project08
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
        
      - name: Install dependencies with pip
        working-directory: ${{env.working-directory}}
        run: |
          pip install -r requirements.txt
          pytest
